"""
Mock vLLM Server — OpenAI-compatible inference server for local testing.

This is a fake vLLM server that responds to the exact same HTTP endpoints
that a real vLLM server exposes when started with:
    vllm serve <model> --port 8100

Use this on machines WITHOUT a GPU (your Mac) to test the full
end-to-end flow:

    Terminal 1 — mock backend (port 8005):
        cd daemon
        python -m tests.mock_backend

    Terminal 2 — mock vLLM (port 8100):
        cd daemon
        python -m tests.mock_vllm

    Terminal 3 — the real daemon:
        cd daemon
        python -m daemon.main --config config.yaml

The mock server:
    - Responds to GET  /health              → 200 OK  (health check)
    - Responds to GET  /v1/models           → lists the fake model
    - Responds to POST /v1/chat/completions → returns a fake but realistic completion
    - Logs every request so you can see the daemon talking to it

The fake responses mirror the exact JSON shape that OpenAI / real vLLM return,
so the daemon's VLLMExecutor parses them identically to the real thing.

Why does the fake response structure matter?
    The daemon reads result["choices"][0]["message"]["content"] for text,
    and result["usage"] for token counts. If any key is missing, the
    daemon silently returns an error. So the mock must be structurally perfect.
"""

from __future__ import annotations

import time
import uuid

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# ── App ──────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Mock vLLM Server",
    description="OpenAI-compatible fake inference server for local daemon testing",
    version="0.1.0",
)

# ── Fake model name ───────────────────────────────────────────────────────────
# The daemon sends the model name from the JSONL body to vLLM.
# We accept ANY model name here — just echo it back.
FAKE_MODEL = "mistralai/Mistral-7B-Instruct-v0.2"

# ── Pre-written fake answers ──────────────────────────────────────────────────
# Instead of returning the same boring string every time, we pick a response
# based on keywords in the user's prompt. Makes the output look realistic.
#
# Each entry is (keyword_substring, answer_text).
# The first match wins. Falls back to the generic answer at the bottom.

_FAKE_ANSWERS: list[tuple[str, str]] = [
    ("capital of france",
     "The capital of France is **Paris**. It has been the capital since 987 AD "
     "and is home to iconic landmarks like the Eiffel Tower, the Louvre, and Notre-Dame Cathedral."),

    ("quantum computing",
     "Quantum computing harnesses quantum mechanical phenomena such as superposition "
     "and entanglement to perform computations that would be infeasible for classical "
     "computers, enabling exponential speedups for certain problem classes."),

    ("haiku",
     "Brackets close the loop,\n"
     "Functions bloom in nested calls,\n"
     "The stack unwinds clean."),

    ("2+2", "2 + 2 = **4**."),

    ("open source",
     "Three key benefits of open source software are:\n"
     "1. **Transparency** — the source code is publicly auditable, improving security trust.\n"
     "2. **Community collaboration** — thousands of contributors can fix bugs and add features.\n"
     "3. **Zero licensing cost** — organizations can deploy and modify software freely, "
     "reducing total cost of ownership."),
]

_GENERIC_ANSWER = (
    "This is a simulated response from the mock vLLM server. "
    "In a real deployment, this text would be generated by the actual language model "
    "running on a GPU. The mock server is structurally identical to a real vLLM server "
    "so the daemon processes this response exactly the same way."
)


def _pick_answer(messages: list[dict]) -> str:
    """
    Choose a realistic fake answer based on the user's message content.

    Looks at all messages in the conversation, concatenates them into one
    lowercase string, then checks for keyword matches.

    This is NOT AI — it's just simple string matching to make the test
    output look more believable than 'fake response 1, fake response 2'.
    """
    # Collect all message text into one searchable string
    all_text = " ".join(
        msg.get("content", "") for msg in messages
    ).lower()

    for keyword, answer in _FAKE_ANSWERS:
        if keyword in all_text:
            return answer

    return _GENERIC_ANSWER


def _count_tokens(text: str) -> int:
    """
    Very rough token estimator: ~1 token per 4 characters.

    Real tokenizers (tiktoken, sentencepiece) are far more accurate,
    but this is good enough for a mock — the daemon only logs token
    counts; it doesn't bill based on them yet.
    """
    return max(1, len(text) // 4)


# ── Routes ────────────────────────────────────────────────────────────────────


@app.get("/health")
async def health():
    """
    Liveness endpoint. The daemon's VLLMExecutor calls this first.

    Real vLLM returns:   {"status": "ok"}
    We do the same.
    """
    print("[mock-vllm] GET /health → 200")
    return JSONResponse(content={"status": "ok"})


@app.get("/v1/models")
async def list_models():
    """
    Model listing endpoint. The daemon falls back to this if /health fails.

    Real vLLM returns an OpenAI-format model list. We return one fake model.
    The daemon only checks the HTTP status code (200 = healthy), not the body.
    """
    print("[mock-vllm] GET /v1/models → 200")
    return JSONResponse(content={
        "object": "list",
        "data": [
            {
                "id": FAKE_MODEL,
                "object": "model",
                "created": int(time.time()),
                "owned_by": "vllm",
            }
        ]
    })


@app.post("/v1/chat/completions")
async def chat_completions(request: Request):
    """
    The main inference endpoint. This is what the daemon calls for every prompt.

    Real vLLM accepts:
        {
            "model": "mistralai/Mistral-7B-Instruct-v0.2",
            "messages": [{"role": "user", "content": "..."}],
            "max_tokens": 512,
            "temperature": 0.7
        }

    Real vLLM returns (OpenAI chat completion format):
        {
            "id": "chatcmpl-...",
            "object": "chat.completion",
            "created": 1234567890,
            "model": "mistralai/Mistral-7B-Instruct-v0.2",
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": "generated text here"
                    },
                    "finish_reason": "stop"
                }
            ],
            "usage": {
                "prompt_tokens": 12,
                "completion_tokens": 48,
                "total_tokens": 60
            }
        }

    We return the exact same structure so the daemon processes it identically.
    """
    body = await request.json()

    model = body.get("model", FAKE_MODEL)
    messages = body.get("messages", [])
    max_tokens = body.get("max_tokens", 512)

    # Pick a realistic fake answer
    answer_text = _pick_answer(messages)

    # Truncate answer to roughly max_tokens (4 chars per token)
    char_limit = max_tokens * 4
    if len(answer_text) > char_limit:
        answer_text = answer_text[:char_limit].rstrip() + "..."

    # Build token usage counts
    prompt_text = " ".join(m.get("content", "") for m in messages)
    prompt_tokens = _count_tokens(prompt_text)
    completion_tokens = _count_tokens(answer_text)

    # Log what arrived so you can see daemon ↔ vLLM communication
    user_content = next(
        (m.get("content", "")[:60] for m in reversed(messages) if m.get("role") == "user"),
        "(no user message)"
    )
    print(
        f"[mock-vllm] POST /v1/chat/completions  "
        f"model={model}  "
        f"max_tokens={max_tokens}  "
        f"prompt=\"{user_content}...\""
    )
    print(
        f"[mock-vllm]   → response: \"{answer_text[:60]}...\"  "
        f"tokens={prompt_tokens}+{completion_tokens}={prompt_tokens+completion_tokens}"
    )

    # Build the exact OpenAI-format response
    response_body = {
        "id": f"chatcmpl-{uuid.uuid4().hex[:12]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": model,
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": answer_text,
                },
                "finish_reason": "stop",
            }
        ],
        "usage": {
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": prompt_tokens + completion_tokens,
        },
    }

    return JSONResponse(content=response_body)


# ── Startup ───────────────────────────────────────────────────────────────────


@app.on_event("startup")
async def startup():
    print("\n" + "=" * 60)
    print("  Mock vLLM Server — OpenAI-compatible inference stub")
    print("=" * 60)
    print(f"  Listening on : http://localhost:8100")
    print(f"  Health check : GET  http://localhost:8100/health")
    print(f"  Models       : GET  http://localhost:8100/v1/models")
    print(f"  Completions  : POST http://localhost:8100/v1/chat/completions")
    print()
    print("  Fake model   :", FAKE_MODEL)
    print("  Pre-written answers for: France, quantum, haiku, 2+2, open source")
    print("  Generic fallback for all other prompts")
    print()
    print("  ⚡ No GPU needed — all responses are instant and simulated")
    print("=" * 60 + "\n")


# ── Entry point ───────────────────────────────────────────────────────────────


def main():
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8100, log_level="warning")


if __name__ == "__main__":
    main()
